# Generated by Django 3.0.5 on 2020-06-18 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50, unique=True, verbose_name='Area')),
                ('xInicial', models.PositiveIntegerField(verbose_name='Posición X cartesiana (punto inicial)')),
                ('xFinal', models.PositiveIntegerField(verbose_name='Posición X cartesiana (punto final)')),
                ('yInicial', models.PositiveIntegerField(verbose_name='Posición Y cartesiana (punto inicial)')),
                ('yFinal', models.PositiveIntegerField(verbose_name='Posición Y cartesiana (punto final)')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción Area')),
                ('indHabilitado', models.BooleanField(default=True, verbose_name='Indicador Habilitado')),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Registro')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Baliza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macDispositivoBaliza', models.CharField(max_length=17, unique=True, verbose_name='MAC Dispositivo Baliza')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción Baliza')),
                ('indHabilitado', models.BooleanField(default=True, verbose_name='Indicador Habilitado')),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('usuarioRegistra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realiza el registro')),
            ],
            options={
                'verbose_name': 'Baliza',
                'verbose_name_plural': 'Balizas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Bracelet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macDispositivo', models.CharField(max_length=17, unique=True, verbose_name='MAC Dispositivo Bracelet')),
                ('major', models.PositiveIntegerField(verbose_name='Major')),
                ('minor', models.PositiveIntegerField(verbose_name='Minor')),
                ('txPower', models.IntegerField(verbose_name='Potencia a un metro de distancia')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción Bracelet')),
                ('indHabilitado', models.BooleanField(default=True, verbose_name='Indicador Habilitado')),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('usuarioRegistra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realiza el registro')),
            ],
            options={
                'verbose_name': 'Bracelet',
                'verbose_name_plural': 'Bracelets',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolUsuario', models.CharField(max_length=50, unique=True, verbose_name='Rol Usuario')),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('usuarioRegistra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realiza el registro')),
            ],
            options={
                'verbose_name': 'Rol Usuario',
                'verbose_name_plural': 'Roles Usuario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indHabilitado', models.BooleanField(default=True, verbose_name='Indicador Habilitado')),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('rolUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baliza.RolUsuario', verbose_name='Rol Usuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSede', models.CharField(max_length=50, unique=True, verbose_name='Nombre Sede')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción Sede')),
                ('indHabilitado', models.BooleanField(default=True, verbose_name='Indicador Habilitado')),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('usuarioRegistra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realiza el registro')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piso', models.PositiveIntegerField(verbose_name='piso')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción piso')),
                ('indHabilitado', models.BooleanField(default=True, verbose_name='Indicador Habilitado')),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baliza.Sede', verbose_name='Sede')),
                ('usuarioRegistra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realiza el registro')),
            ],
            options={
                'verbose_name': 'piso',
                'verbose_name_plural': 'Pisos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InstalacionBaliza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instalacionX', models.PositiveIntegerField(verbose_name='Posición X cartesiana (punto instalación)')),
                ('instalacionY', models.PositiveIntegerField(verbose_name='Posición Y cartesiana (punto instalación)')),
                ('indHabilitado', models.BooleanField(default=True, verbose_name='Indicador Habilitado')),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('baliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baliza.Baliza', verbose_name='Baliza')),
                ('piso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baliza.Piso', verbose_name='piso')),
                ('usuarioRegistra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realiza el registro')),
            ],
            options={
                'verbose_name': 'Instalación Baliza',
                'verbose_name_plural': 'Instalación Balizas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistorialUbicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaIngresoArea', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Ingreso Area')),
                ('fechaSalidaArea', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Salida Area')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baliza.Area', verbose_name='Area')),
                ('bracelet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baliza.Bracelet', verbose_name='Bracelet')),
            ],
            options={
                'verbose_name': 'Historial Ubicacion',
                'verbose_name_plural': 'Historial Ubicaciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistorialRSSI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rssi_signal', models.IntegerField(verbose_name='Intensidad señal BLE (RSSI)')),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('baliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baliza.Baliza', verbose_name='Baliza')),
                ('bracelet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baliza.Bracelet', verbose_name='Bracelet')),
            ],
            options={
                'verbose_name': 'Historial RSSI',
                'verbose_name_plural': 'Historials RRSI',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HistorialBraceletSensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppm_sensor', models.PositiveIntegerField(verbose_name='Pulso cardiaco persona')),
                ('caida_sensor', models.BooleanField(verbose_name='Detección caídas de la persona')),
                ('proximidad_sensor', models.BooleanField(default=True, verbose_name='Sensor proximidad para detectar ManillaPuesta en la persona')),
                ('temperatura_sensor', models.PositiveIntegerField(verbose_name='Temperatura persona')),
                ('nivel_bateria', models.PositiveIntegerField(verbose_name='Porcentaje nivel Bateria')),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('baliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baliza.Baliza', verbose_name='Baliza')),
                ('bracelet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baliza.Bracelet', verbose_name='Bracelet')),
            ],
            options={
                'verbose_name': 'Historial Bracelet Sensors',
                'verbose_name_plural': 'Historials Bracelet Sensors',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BraceletUmbrals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimaTemperatura', models.PositiveIntegerField(verbose_name='Temperatura minima')),
                ('maximaTemperatura', models.PositiveIntegerField(verbose_name='Temperatura maxima')),
                ('minimoPulsoCardiaco', models.PositiveIntegerField(verbose_name='Pulso Cardiaco minimo')),
                ('maximaPulsoCardiaco', models.PositiveIntegerField(verbose_name='Pulso Cardiaco maximo')),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('bracelet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baliza.Bracelet', verbose_name='Bracelet')),
                ('usuarioRegistra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realiza el registro')),
            ],
            options={
                'verbose_name': 'Bracele tUmbral',
                'verbose_name_plural': 'Bracelet Umbrales',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BraceletPatienHospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDatosPaciente', models.CharField(max_length=50, unique=True, verbose_name='Id datos almacenados que identifican al paciente')),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('bracelet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baliza.Bracelet', verbose_name='Bracelet')),
                ('usuarioRegistra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realiza el registro')),
            ],
            options={
                'verbose_name': 'Bracelet Patien Hospital',
                'verbose_name_plural': 'Bracelet Patiens Hospital',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='area',
            name='piso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baliza.Piso', verbose_name='piso'),
        ),
        migrations.AddField(
            model_name='area',
            name='usuarioRegistra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realiza el registro'),
        ),
    ]
